fixtures:
  repositories:
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.6.0'
    rpcbind:
      repo: 'git://github.com/ghoneycutt/puppet-module-rpcbind.git'
      ref: 'v1.4.0'
  symlinks:
    nfsclient: "#{source_dir}"
